version: "3.8"

services:
  web:
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    build: .
    command: bash -c "ls -al && gunicorn greenbudget.wsgi -c /app/greenbudget/conf/gunicorn_config.py"
    restart: always
    networks:
      - greenbudget
    ports:
      - "8000:8000"
    # Note if you have trouble with Windows try mounting volumes in this format
    volumes:
      - type: bind
        source: ./src
        target: /app
    env_file:
      - .env

  db:
    restart: "no"
    build: './postgres'
    ports:
      - "5432:5432"
    networks:
      - greenbudget
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

networks:
  greenbudget:
    driver: bridge
