version: "3.3"

services:
  web:
    environment:
      DJANGO_SETTINGS_MODULE: happybudget.conf.settings.prod
    build: .
    command: bash -c "ls -al && gunicorn happybudget.wsgi -c /app/happybudget/conf/gunicorn_config.py"
    restart: always
    networks:
      - happybudget
    ports:
      - "8000:8000"
    # Note if you have trouble with Windows try mounting volumes in this format
    volumes:
      - type: bind
        source: ./src
        target: /app
    env_file:
      - .env

networks:
  happybudget:
    driver: bridge
