# Generated by Django 3.1.7 on 2021-09-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='content_types',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'group'), ('model', 'group')), models.Q(('app_label', 'fringe'), ('model', 'fringe')), models.Q(('app_label', 'subaccount'), ('model', 'subaccountunit')), _connector='OR'), to='contenttypes.ContentType'),
        ),
    ]
