version: 2

orbs:
  poetry: frameio/poetry@0.15.0

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.8

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages

      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}

      - run:
          name: Install Dependencies
          command: |
            poetry install

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
            - "/home/circleci/.cache/pypoetry/virtualenvs"

      - run:
          name: Run Linting Checks
          command: |
            poetry run flake8 src/greenbudget

      - run:
          name: Run Tests
          command: >-
            poetry run coverage erase
            poetry run coverage run --parallel -m pytest
            poetry run coverage combine
            poetry run coverage report
            poetry run coverage xml
            poetry run coverage html


workflows:
  version: 2

  build-and-test-workflow:
    jobs:
      - build-and-test