version: 2

orbs:
  poetry: frameio/poetry@0.15.0
  python: circleci/python@0.2.1
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/python:3.8.8
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          name: Install Dependencies
          command: |
            poetry install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
            - "/home/circleci/.cache/pypoetry/virtualenvs"
      - run:
          name: Run Linting Checks
          command: |
            poetry run flake8 src/greenbudget
      - run:
          name: "Establish Test Result Directories"
          command: |
            mkdir -p ~/reports/test-results
      - run:
          name: Run Tests
          command: >-
            poetry run coverage run --parallel -m pytest --junit-xml=~/reports/test-results/pytest.xml
      - store_test_results:
          path: ~/reports/test-results

workflows:
  version: 2

  build-test-and-deploy:
    jobs:
      - build