version: 2

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.8

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - deps-{{ checksum "poetry.lock" }}

      # - run:
      #     name: Install Dependencies
      #     command: |
      #       poetry install

      # Save's the specified path as a cache. This is the path Poetry uses to install the dependencies
      # So if you don't install anything new, this folder won't change and the cache will be effective
      # - save_cache:
      #     key: deps-{{ checksum "poetry.lock" }}
      #     paths:
      #       - /home/circleci/.cache/pypoetry/virtualenvs

      # Another step, run flake8
      - run:
          name: Run Linting Checks
          command: |
            tox -e lint

      # Last step, runs our tests ommiting the dependencies path (so we don't take their coverage into account)
      # And send our coverage somewhere, in this case, coveralls
      - run:
          name: Run Tests
          command: |
            tox -e test

workflows:
  version: 2

  build-and-test-workflow:
    jobs:
      - build-and-test