# Generated by Django 3.1.7 on 2021-03-02 03:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0002_auto_20210302_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'get_latest_by': 'created_at', 'ordering': ('-created_at',), 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('author', 'name')},
        ),
    ]
