# Generated by Django 3.1.7 on 2021-03-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20210302_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'get_latest_by': 'updated_at', 'ordering': ('-updated_at',), 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
