# Generated by Django 3.1.7 on 2021-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20210302_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
