# Generated by Django 3.1.7 on 2021-03-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('budget_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('budgetitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget_item.budgetitem')),
                ('name', models.CharField(max_length=128, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('multiplier', models.IntegerField(null=True)),
                ('unit', models.IntegerField(choices=[(0, 'Minutes'), (1, 'Hours'), (2, 'Weeks'), (3, 'Months'), (4, 'Days'), (5, 'Nights')], null=True)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'account'), ('model', 'account')), models.Q(('app_label', 'subaccount'), ('model', 'subaccount')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Sub Account',
                'verbose_name_plural': 'Sub Accounts',
                'ordering': ('created_at',),
                'get_latest_by': 'updated_at',
            },
            bases=('budget_item.budgetitem',),
        ),
    ]
