# Generated by Django 3.1.7 on 2021-04-18 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('multiplier', models.IntegerField(null=True)),
                ('unit', models.IntegerField(choices=[(0, 'Minutes'), (1, 'Hours'), (2, 'Weeks'), (3, 'Months'), (4, 'Days'), (5, 'Nights'), (6, 'Allow'), (7, 'Flat'), (8, 'Feet'), (9, 'Fare'), (10, 'Units')], null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to='budget.basebudget')),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'account'), ('model', 'Account')), models.Q(('app_label', 'subaccount'), ('model', 'SubAccount')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_subaccount.subaccount_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Sub Account',
                'verbose_name_plural': 'Sub Accounts',
                'ordering': ('created_at',),
                'get_latest_by': 'updated_at',
                'unique_together': {('content_type', 'object_id', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='TemplateSubAccount',
            fields=[
                ('subaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subaccount.subaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_template_sub_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_template_sub_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Sub Account',
                'verbose_name_plural': 'Template Sub Accounts',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('subaccount.subaccount',),
        ),
        migrations.CreateModel(
            name='BudgetSubAccount',
            fields=[
                ('subaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subaccount.subaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_sub_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budget_sub_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Sub Account',
                'verbose_name_plural': 'Budget Sub Accounts',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('subaccount.subaccount',),
        ),
    ]
