# Generated by Django 3.1.7 on 2021-03-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('subaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subaccount',
            unique_together={('object_id', 'content_type', 'name')},
        ),
    ]
