# Generated by Django 3.1.7 on 2021-03-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('subaccount', '0002_add_uniqueness_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to='budget.budget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
