# Generated by Django 3.1.7 on 2021-06-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subaccount', '0011_rename_unit_new_to_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsubaccount',
            options={'base_manager_name': 'objects', 'verbose_name': 'Sub Account', 'verbose_name_plural': 'Sub Accounts'},
        ),
        migrations.AlterModelOptions(
            name='templatesubaccount',
            options={'base_manager_name': 'objects', 'verbose_name': 'Sub Account', 'verbose_name_plural': 'Sub Accounts'},
        ),
    ]
