# Generated by Django 3.1.7 on 2021-09-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subaccount', '0024_rename_new_parent_created_by_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsubaccount',
            options={'base_manager_name': 'objects', 'verbose_name': 'Budget Sub Account', 'verbose_name_plural': 'Budget Sub Accounts'},
        ),
        migrations.AlterModelOptions(
            name='templatesubaccount',
            options={'base_manager_name': 'objects', 'verbose_name': 'Template Sub Account', 'verbose_name_plural': 'Template Sub Accounts'},
        ),
    ]
