# Generated by Django 3.1.7 on 2021-03-19 15:24

from django.db import migrations, models
import greenbudget.app.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=greenbudget.app.user.models.upload_to),
        ),
    ]
