# Generated by Django 3.1.7 on 2021-03-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitybudgetitem',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
