# Generated by Django 3.1.7 on 2021-03-27 19:42

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_budget_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BudgetItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', colorful.fields.RGBColorField(colors=['#797695', '#ff7165', '#80cbc4', '#ce93d8', '#fed835', '#c87987', '#69f0ae', '#a1887f', '#81d4fa', '#f75776', '#66bb6a', '#58add6'], default='#EFEFEF')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_budget_item.budgetitemgroup_set+', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Item Group',
                'verbose_name_plural': 'Budget Item Groups',
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
            },
        ),
    ]
