# Generated by Django 3.1.7 on 2021-11-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_meta_options'),
        ('actual', '0014_latest_by_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actual',
            unique_together={('budget', 'order')},
        ),
    ]
