import pytest

from .factories import UserFactory, BudgetFactory


@pytest.fixture
def create_user():
    """
    A fixture that creates a :obj:`User` instance using the
    :obj:`UserFactory`.  Any data that is not explicitly provided will
    be randomly generated by the factory.

    Usage:
    -----
    >>> def test_user(create_user):
    >>>     user = create_user(first_name="jack")
    >>>     assert user.first_name == "jack"
    """
    def inner(*args, **kwargs):
        return UserFactory(*args, **kwargs)
    return inner


@pytest.fixture
def create_budget(user):
    """
    A fixture that creates a :obj:`Budget` instance using the
    :obj:`BudgetFactory`.  Any data that is not explicitly provided will
    be randomly generated by the factory.

    Usage:
    -----
    >>> def test_budget(create_budget):
    >>>     budget = create_budget(name='Test Budget')
    >>>     assert budget.name == 'Test Budget'
    """
    def inner(*args, **kwargs):
        kwargs.setdefault('author', user)
        return BudgetFactory(*args, **kwargs)
    return inner
