# Generated by Django 3.1.7 on 2021-04-18 02:38

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', colorful.fields.RGBColorField(colors=['#797695', '#ff7165', '#80cbc4', '#ce93d8', '#fed835', '#c87987', '#69f0ae', '#a1887f', '#81d4fa', '#f75776', '#66bb6a', '#58add6'], default='#EFEFEF')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_group.group_set+', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='TemplateSubAccountGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.group')),
                ('name', models.CharField(max_length=128)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'subaccount'), ('model', 'templatesubaccount')), models.Q(('app_label', 'account'), ('model', 'templateaccount')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Template Sub Account Group',
                'verbose_name_plural': 'Template Sub Account Groups',
                'abstract': False,
                'base_manager_name': 'objects',
                'unique_together': {('object_id', 'content_type', 'name')},
            },
            bases=('group.group',),
        ),
        migrations.CreateModel(
            name='TemplateAccountGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.group')),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='template.template')),
            ],
            options={
                'verbose_name': 'Template Account Group',
                'verbose_name_plural': 'Template Account Groups',
                'abstract': False,
                'base_manager_name': 'objects',
                'unique_together': {('parent', 'name')},
            },
            bases=('group.group',),
        ),
        migrations.CreateModel(
            name='BudgetSubAccountGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.group')),
                ('name', models.CharField(max_length=128)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'subaccount'), ('model', 'budgetsubaccount')), models.Q(('app_label', 'account'), ('model', 'budgetaccount')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Budget Sub Account Group',
                'verbose_name_plural': 'Budget Sub Account Groups',
                'abstract': False,
                'base_manager_name': 'objects',
                'unique_together': {('object_id', 'content_type', 'name')},
            },
            bases=('group.group',),
        ),
        migrations.CreateModel(
            name='BudgetAccountGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.group')),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='budget.budget')),
            ],
            options={
                'verbose_name': 'Budget Account Group',
                'verbose_name_plural': 'Budget Account Groups',
                'abstract': False,
                'base_manager_name': 'objects',
                'unique_together': {('parent', 'name')},
            },
            bases=('group.group',),
        ),
    ]
