# Generated by Django 3.1.7 on 2021-06-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_relax_field_requirements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
