# Generated by Django 3.1.7 on 2021-11-21 19:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0015_latest_by_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('created_by', 'order')},
        ),
    ]
