# Generated by Django 3.1.7 on 2021-03-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldalterationevent',
            name='new_value',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldalterationevent',
            name='old_value',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
