# Generated by Django 3.1.7 on 2021-06-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_template_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('community', True), ('hidden', False)), models.Q(('community', True), ('hidden', True)), models.Q(('community', False), ('hidden', False)), _connector='OR'), name='template_template_hidden_only_for_community'),
        ),
    ]
