FROM postgres:10.7-alpine

# RUN apk add --no-cache openssl curl py-pip postgresql-dev make gcc musl-dev && pip install pgxnclient && pgxnclient install temporal_tables

RUN \
    apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
    apk --purge del .build-deps
